ALTER TABLE address
    MODIFY COLUMN cep VARCHAR(9) NOT NULL,
    MODIFY COLUMN city VARCHAR(50) NOT NULL,
    MODIFY COLUMN complement VARCHAR(50),
    MODIFY COLUMN neighborhood VARCHAR(50) NOT NULL,
    MODIFY COLUMN number VARCHAR(10) NOT NULL,
    MODIFY COLUMN state VARCHAR(50) NOT NULL,
    MODIFY COLUMN street VARCHAR(255) NOT NULL;

ALTER TABLE product
    ADD COLUMN active TINYINT NULL AFTER product_type,
    MODIFY COLUMN category VARCHAR(50) NOT NULL,
    MODIFY COLUMN description VARCHAR(255) NOT NULL,
    MODIFY COLUMN inventory INTEGER NOT NULL,
    MODIFY COLUMN name VARCHAR(255) NOT NULL,
    MODIFY COLUMN price DECIMAL(19, 2) NOT NULL,
    MODIFY COLUMN product_type VARCHAR(255) NOT NULL;

ALTER TABLE department
    MODIFY COLUMN name VARCHAR(20) NOT NULL;

ALTER TABLE user
    MODIFY COLUMN email VARCHAR(50) NOT NULL,
    MODIFY COLUMN name VARCHAR(255) NOT NULL,
    MODIFY COLUMN password VARCHAR(50) NOT NULL;

ALTER TABLE product_department
    MODIFY COLUMN department_id BIGINT NOT NULL;

